# Generated by Django 5.0.7 on 2024-07-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='サークル名')),
                ('logo', models.ImageField(upload_to='images/logo/', verbose_name='ロゴ')),
                ('image', models.ImageField(upload_to='images/circle_images/', verbose_name='活動写真')),
                ('order', models.FloatField(default=0, verbose_name='優先順位')),
                ('location', models.CharField(max_length=20, verbose_name='活動場所')),
                ('introduction', models.CharField(max_length=1000, verbose_name='紹介文')),
                ('account', models.URLField()),
            ],
        ),
    ]
