# Generated by Django 5.0.7 on 2024-07-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circles',
            name='account',
        ),
        migrations.RemoveField(
            model_name='circles',
            name='image',
        ),
        migrations.AlterField(
            model_name='circles',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='ロゴ'),
        ),
    ]
