# Generated by Django 5.0.7 on 2024-07-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_circles_account_remove_circles_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circles',
            new_name='Circle',
        ),
    ]
