# Generated by Django 5.0.7 on 2024-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_circles_circle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='ニックネーム')),
                ('time', models.IntegerField(verbose_name='0:01:23.45の形で')),
            ],
        ),
    ]
