# Generated by Django 5.0.7 on 2024-09-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ニックネーム'),
        ),
    ]
