# Generated by Django 5.0.7 on 2024-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ranking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='time',
            field=models.DurationField(verbose_name='0:01:23.45の形で'),
        ),
    ]
